# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            modess.io
tagline:          ''
description:      >
  <p class="lead">
    My name is Niklas Modess, I'm a PHP developer and consultant based in Stockholm, Sweden.
  </p> 
  <p class="lead">
    I'm a Laravel/AngularJS/ReactJS enthusiast, author of <a href="https://leanpub.com/deploying-php-applications">Deploying PHP Applications</a>, 
    creator of <a href="https://github.com/modess/git-pretty-stats">Git Pretty Stats</a>. 
    Organizer for <a href="http://www.meetup.com/Laravel-Stockholm/">Laravel Stockholm</a>.
  </p>
url:              http://modess.io
baseurl:          /

author:
  name:           'Niklas Modess'
  url:            https://twitter.com/niklasmodess

paginate:         5